"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Member = exports.createMemberProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Member} interface.
 * All required methods in {@link MemberInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMemberProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.reflect.Member', methods, opts);
}
exports.createMemberProxy = createMemberProxy;
/**
 * Class java.lang.reflect.Member.
 *
 * This actually imports the java class for further use.
 * The class {@link MemberClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Member extends (0, java_bridge_1.importClass)('java.lang.reflect.Member') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Member = Member;
exports.default = Member;
//# sourceMappingURL=Member.js.map