"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RetrieveAuditInject = exports.createRetrieveAuditInjectProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link RetrieveAuditInject} interface.
 * All required methods in {@link RetrieveAuditInjectInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createRetrieveAuditInjectProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.github.chinlinlee.dcm777.dcmqrscp.RetrieveAuditInject', methods, opts);
}
exports.createRetrieveAuditInjectProxy = createRetrieveAuditInjectProxy;
/**
 * Class org.github.chinlinlee.dcm777.dcmqrscp.RetrieveAuditInject.
 *
 * This actually imports the java class for further use.
 * The class {@link RetrieveAuditInjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class RetrieveAuditInject extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.dcmqrscp.RetrieveAuditInject') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.RetrieveAuditInject = RetrieveAuditInject;
exports.default = RetrieveAuditInject;
