"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileOutputStream = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.io.FileOutputStream.
 *
 * This actually imports the java class for further use.
 * The class {@link FileOutputStreamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FileOutputStream extends (0, java_bridge_1.importClass)('java.io.FileOutputStream') {
}
exports.FileOutputStream = FileOutputStream;
exports.default = FileOutputStream;
//# sourceMappingURL=FileOutputStream.js.map