"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ObjectOutput = exports.createObjectOutputProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ObjectOutput} interface.
 * All required methods in {@link ObjectOutputInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createObjectOutputProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.io.ObjectOutput', methods, opts);
}
exports.createObjectOutputProxy = createObjectOutputProxy;
/**
 * Class java.io.ObjectOutput.
 *
 * This actually imports the java class for further use.
 * The class {@link ObjectOutputClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ObjectOutput extends (0, java_bridge_1.importClass)('java.io.ObjectOutput') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ObjectOutput = ObjectOutput;
exports.default = ObjectOutput;
//# sourceMappingURL=ObjectOutput.js.map