"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ObjectInput = exports.createObjectInputProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ObjectInput} interface.
 * All required methods in {@link ObjectInputInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createObjectInputProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.io.ObjectInput', methods, opts);
}
exports.createObjectInputProxy = createObjectInputProxy;
/**
 * Class java.io.ObjectInput.
 *
 * This actually imports the java class for further use.
 * The class {@link ObjectInputClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ObjectInput extends (0, java_bridge_1.importClass)('java.io.ObjectInput') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ObjectInput = ObjectInput;
exports.default = ObjectInput;
//# sourceMappingURL=ObjectInput.js.map