"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RandomAccessFile = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.io.RandomAccessFile.
 *
 * This actually imports the java class for further use.
 * The class {@link RandomAccessFileClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class RandomAccessFile extends (0, java_bridge_1.importClass)('java.io.RandomAccessFile') {
}
exports.RandomAccessFile = RandomAccessFile;
exports.default = RandomAccessFile;
//# sourceMappingURL=RandomAccessFile.js.map