"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemporalAccessor = exports.createTemporalAccessorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link TemporalAccessor} interface.
 * All required methods in {@link TemporalAccessorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createTemporalAccessorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.time.temporal.TemporalAccessor', methods, opts);
}
exports.createTemporalAccessorProxy = createTemporalAccessorProxy;
/**
 * Class java.time.temporal.TemporalAccessor.
 *
 * This actually imports the java class for further use.
 * The class {@link TemporalAccessorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TemporalAccessor extends (0, java_bridge_1.importClass)('java.time.temporal.TemporalAccessor') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TemporalAccessor = TemporalAccessor;
exports.default = TemporalAccessor;
//# sourceMappingURL=TemporalAccessor.js.map