"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemporalQuery = exports.createTemporalQueryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link TemporalQuery} interface.
 * All required methods in {@link TemporalQueryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createTemporalQueryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.time.temporal.TemporalQuery', methods, opts);
}
exports.createTemporalQueryProxy = createTemporalQueryProxy;
/**
 * Class java.time.temporal.TemporalQuery.
 *
 * This actually imports the java class for further use.
 * The class {@link TemporalQueryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TemporalQuery extends (0, java_bridge_1.importClass)('java.time.temporal.TemporalQuery') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TemporalQuery = TemporalQuery;
exports.default = TemporalQuery;
//# sourceMappingURL=TemporalQuery.js.map