"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReadableByteChannel = exports.createReadableByteChannelProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ReadableByteChannel} interface.
 * All required methods in {@link ReadableByteChannelInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createReadableByteChannelProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.nio.channels.ReadableByteChannel', methods, opts);
}
exports.createReadableByteChannelProxy = createReadableByteChannelProxy;
/**
 * Class java.nio.channels.ReadableByteChannel.
 *
 * This actually imports the java class for further use.
 * The class {@link ReadableByteChannelClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ReadableByteChannel extends (0, java_bridge_1.importClass)('java.nio.channels.ReadableByteChannel') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ReadableByteChannel = ReadableByteChannel;
exports.default = ReadableByteChannel;
//# sourceMappingURL=ReadableByteChannel.js.map