import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link UID} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class UIDClass extends JavaClass {
    /**
     * Original type: 'java.lang.String'
     */
    static readonly Verification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplicitVRLittleEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ExplicitVRLittleEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedUncompressedExplicitVRLittleEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DeflatedExplicitVRLittleEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ExplicitVRBigEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGBaseline8Bit: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGExtended12Bit: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGExtended35: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGSpectralSelectionNonHierarchical68: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGSpectralSelectionNonHierarchical79: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGFullProgressionNonHierarchical1012: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGFullProgressionNonHierarchical1113: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLosslessNonHierarchical15: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGExtendedHierarchical1618: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGExtendedHierarchical1719: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGSpectralSelectionHierarchical2022: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGSpectralSelectionHierarchical2123: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGFullProgressionHierarchical2426: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGFullProgressionHierarchical2527: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLosslessHierarchical28: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLosslessHierarchical29: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLosslessSV1: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLSLossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEGLSNearLossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEG2000Lossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEG2000: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEG2000MCLossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPEG2000MC: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPIPReferenced: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly JPIPReferencedDeflate: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG2MPML: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG2MPMLF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG2MPHL: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG2MPHLF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP41: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP41F: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP41BD: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP41BDF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP422D: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP422DF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP423D: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP423DF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP42STEREO: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MPEG4HP42STEREOF: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HEVCMP51: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HEVCM10P51: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RLELossless: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RFC2557MIMEEncapsulation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XMLEncoding: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SMPTEST211020UncompressedProgressiveActiveVideo: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SMPTEST211020UncompressedInterlacedActiveVideo: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SMPTEST211030PCMDigitalAudio: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MediaStorageDirectoryStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HotIronPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PETPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HotMetalBluePalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PET20StepPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SpringPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SummerPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly FallPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly WinterPalette: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicStudyContentNotification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly Papyrus3ImplicitVRLittleEndian: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StorageCommitmentPushModel: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StorageCommitmentPushModelInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StorageCommitmentPullModel: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StorageCommitmentPullModelInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProceduralEventLogging: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProceduralEventLoggingInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SubstanceAdministrationLogging: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SubstanceAdministrationLoggingInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DCMUID: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DCM: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MA: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UBERON: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ITIS_TSN: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MGI: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PUBCHEM_CID: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DC: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly NYUMCCG: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MAYONRISBSASRG: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly IBSI: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RO: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RADELEMENT: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly I11: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UNS: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RRID: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOMApplicationContext: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedPatientManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedPatientManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedVisitManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedStudyManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StudyComponentManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ModalityPerformedProcedureStep: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ModalityPerformedProcedureStepRetrieve: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ModalityPerformedProcedureStepNotification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedResultsManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedResultsManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedStudyManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetachedInterpretationManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly Storage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicFilmSession: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicFilmBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicGrayscaleImageBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicColorImageBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ReferencedImageBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicGrayscalePrintManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ReferencedGrayscalePrintManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrintJob: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicAnnotationBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly Printer: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrinterConfigurationRetrieval: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrinterInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrinterConfigurationRetrievalInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicColorPrintManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ReferencedColorPrintManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VOILUTBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PresentationLUT: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImageOverlayBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicPrintImageOverlayBox: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrintQueueInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrintQueueManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StoredPrintStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HardcopyGrayscaleImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HardcopyColorImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PullPrintRequest: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PullStoredPrintManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MediaCreationManagement: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DisplaySystem: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DisplaySystemInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ComputedRadiographyImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalXRayImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalXRayImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalMammographyXRayImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalMammographyXRayImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalIntraOralXRayImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DigitalIntraOralXRayImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedCTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly LegacyConvertedEnhancedCTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UltrasoundMultiFrameImageStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UltrasoundMultiFrameImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MRImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedMRImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MRSpectroscopyStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedMRColorImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly LegacyConvertedEnhancedMRImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly NuclearMedicineImageStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UltrasoundImageStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UltrasoundImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedUSVolumeStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SecondaryCaptureImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultiFrameSingleBitSecondaryCaptureImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultiFrameGrayscaleByteSecondaryCaptureImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultiFrameGrayscaleWordSecondaryCaptureImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultiFrameTrueColorSecondaryCaptureImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StandaloneOverlayStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StandaloneCurveStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly WaveformStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TwelveLeadECGWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralECGWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AmbulatoryECGWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HemodynamicWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CardiacElectrophysiologyWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicVoiceAudioWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralAudioWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ArterialPulseWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RespiratoryWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultichannelRespiratoryWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RoutineScalpElectroencephalogramWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ElectromyogramWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ElectrooculogramWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SleepElectroencephalogramWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BodyPositionWaveformStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StandaloneModalityLUTStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StandaloneVOILUTStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GrayscaleSoftcopyPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColorSoftcopyPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PseudoColorSoftcopyPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BlendingSoftcopyPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XAXRFGrayscaleSoftcopyPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GrayscalePlanarMPRVolumetricPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CompositingPlanarMPRVolumetricPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AdvancedBlendingPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VolumeRenderingVolumetricPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SegmentedVolumeRenderingVolumetricPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MultipleVolumeRenderingVolumetricPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRayAngiographicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedXAImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRayRadiofluoroscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedXRFImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRayAngiographicBiPlaneImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ZeissOPTFile: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRay3DAngiographicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRay3DCraniofacialImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BreastTomosynthesisImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BreastProjectionXRayImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BreastProjectionXRayImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly IntravascularOpticalCoherenceTomographyImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly IntravascularOpticalCoherenceTomographyImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly NuclearMedicineImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ParametricMapStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MRImageStorageZeroPadded: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RawDataStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SpatialRegistrationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SpatialFiducialsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DeformableSpatialRegistrationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SegmentationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SurfaceSegmentationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TractographyResultsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RealWorldValueMappingStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SurfaceScanMeshStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SurfaceScanPointCloudStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLImageStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLMultiFrameImageStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLEndoscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VideoEndoscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLMicroscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VideoMicroscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLSlideCoordinatesMicroscopicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLPhotographicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VideoPhotographicImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicPhotography8BitImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicPhotography16BitImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StereometricRelationshipStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicTomographyImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly WideFieldOphthalmicPhotographyStereographicProjectionImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly WideFieldOphthalmicPhotography3DCoordinatesImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicOpticalCoherenceTomographyEnFaceImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VLWholeSlideMicroscopyImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DermoscopicPhotographyImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly LensometryMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AutorefractionMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly KeratometryMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SubjectiveRefractionMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VisualAcuityMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SpectaclePrescriptionReportStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicAxialMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly IntraocularLensCalculationsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MacularGridThicknessAndVolumeReportStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicVisualFieldStaticPerimetryMeasurementsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly OphthalmicThicknessMapStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CornealTopographyMapStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TextSRStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AudioSRStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DetailSRStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ComprehensiveSRStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicTextSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ComprehensiveSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly Comprehensive3DSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ExtensibleSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProcedureLogStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MammographyCADSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly KeyObjectSelectionDocumentStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ChestCADSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XRayRadiationDoseSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RadiopharmaceuticalRadiationDoseSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColonCADSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantationPlanSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AcquisitionContextSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SimplifiedAdultEchoSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientRadiationDoseSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PlannedImagingAgentAdministrationSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PerformedImagingAgentAdministrationSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedXRayRadiationDoseSRStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ContentAssessmentResultsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly MicroscopyBulkSimpleAnnotationsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedPDFStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedCDAStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedSTLStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedOBJStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EncapsulatedMTLStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PositronEmissionTomographyImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly LegacyConvertedEnhancedPETImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StandalonePETCurveStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedPETImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BasicStructuredDisplayStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CTDefinedProcedureProtocolStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CTPerformedProcedureProtocolStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProtocolApprovalStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProtocolApprovalInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProtocolApprovalInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProtocolApprovalInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XADefinedProcedureProtocolStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly XAPerformedProcedureProtocolStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InventoryStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InventoryFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InventoryMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InventoryGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InventoryCreation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RepositoryQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StorageManagementInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTDoseStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTStructureSetStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTBeamsTreatmentRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTPlanStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTBrachyTreatmentRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTTreatmentSummaryRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTIonPlanStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTIonBeamsTreatmentRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTPhysicianIntentStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTSegmentAnnotationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTRadiationSetStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CArmPhotonElectronRadiationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TomotherapeuticRadiationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RoboticArmRadiationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTRadiationRecordSetStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTRadiationSalvageRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TomotherapeuticRadiationRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CArmPhotonElectronRadiationRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RoboticRadiationRecordStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTRadiationSetDeliveryInstructionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTTreatmentPreparationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedRTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EnhancedContinuousRTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTPatientPositionAcquisitionInstructionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOSCTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOSDigitalXRayImageStorageForPresentation: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOSDigitalXRayImageStorageForProcessing: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOSThreatDetectionReportStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOS2DAITStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOS3DAITStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOSQuadrupoleResonanceStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EddyCurrentImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly EddyCurrentMultiFrameImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientRootQueryRetrieveInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientRootQueryRetrieveInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientRootQueryRetrieveInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StudyRootQueryRetrieveInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StudyRootQueryRetrieveInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly StudyRootQueryRetrieveInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientStudyOnlyQueryRetrieveInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientStudyOnlyQueryRetrieveInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PatientStudyOnlyQueryRetrieveInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CompositeInstanceRootRetrieveMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CompositeInstanceRootRetrieveGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CompositeInstanceRetrieveWithoutBulkDataGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DefinedProcedureProtocolInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DefinedProcedureProtocolInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DefinedProcedureProtocolInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ModalityWorklistInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralPurposeWorklistManagementMeta: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralPurposeWorklistInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralPurposeScheduledProcedureStep: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralPurposePerformedProcedureStep: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly InstanceAvailabilityNotification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTBeamsDeliveryInstructionStorageTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTConventionalMachineVerificationTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTIonMachineVerificationTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedWorklistAndProcedureStepTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepPushTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepWatchTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepPullTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepEventTrial: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UPSGlobalSubscriptionInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UPSFilteredGlobalSubscriptionInstance: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedWorklistAndProcedureStep: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepPush: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepWatch: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepPull: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepEvent: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UnifiedProcedureStepQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTBeamsDeliveryInstructionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTConventionalMachineVerification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTIonMachineVerification: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RTBrachyApplicationSetupDeliveryInstructionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GeneralRelevantPatientInformationQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly BreastImagingRelevantPatientInformationQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly CardiacRelevantPatientInformationQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HangingProtocolStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HangingProtocolInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HangingProtocolInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly HangingProtocolInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColorPaletteStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColorPaletteQueryRetrieveInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColorPaletteQueryRetrieveInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ColorPaletteQueryRetrieveInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ProductCharacteristicsQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly SubstanceApprovalQuery: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GenericImplantTemplateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GenericImplantTemplateInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GenericImplantTemplateInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly GenericImplantTemplateInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantAssemblyTemplateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantAssemblyTemplateInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantAssemblyTemplateInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantAssemblyTemplateInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantTemplateGroupStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantTemplateGroupInformationModelFind: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantTemplateGroupInformationModelMove: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly ImplantTemplateGroupInformationModelGet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly NativeDICOMModel: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AbstractMultiDimensionalImageModel: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly DICOMContentMappingResource: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VideoEndoscopicImageRealTimeCommunication: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VideoPhotographicImageRealTimeCommunication: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly AudioWaveformRealTimeCommunication: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly RenditionSelectionDocumentRealTimeCommunication: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomDeviceName: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomDescription: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomManufacturer: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomManufacturerModelName: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomSoftwareVersion: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomVendorData: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomAETitle: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomNetworkConnectionReference: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomApplicationCluster: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomAssociationInitiator: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomAssociationAcceptor: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomHostname: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomPort: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomSOPClass: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomTransferRole: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomTransferSyntax: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomPrimaryDeviceType: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomRelatedDeviceReference: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomPreferredCalledAETitle: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomTLSCyphersuite: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomAuthorizedNodeCertificateReference: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomThisNodeCertificateReference: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomInstalled: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomStationName: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomDeviceSerialNumber: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomInstitutionName: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomInstitutionAddress: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomInstitutionDepartmentName: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomIssuerOfPatientID: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomPreferredCallingAETitle: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomSupportedCharacterSet: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomConfigurationRoot: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomDevicesRoot: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomUniqueAETitlesRegistryRoot: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomDevice: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomNetworkAE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomNetworkConnection: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomUniqueAETitle: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly dicomTransferCapability: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UTC: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateDcm4cheEncapsulatedGenozipStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateAgfaBasicAttributePresentationState: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateAgfaArrivalTransaction: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateAgfaDictationTransaction: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateAgfaReportTranscriptionTransaction: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateAgfaReportApprovalTransaction: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateTomTecAnnotationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateToshibaUSImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateFujiCRImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGECollageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateERADPracticeBuilderReportTextStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateERADPracticeBuilderReportDictationStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsHPLive3D01Storage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsHPLive3D02Storage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGE3DModelStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGEDicomCTImageInfoObject: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGEDicomDisplayImageInfoObject: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGEDicomMRImageInfoObject: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGEeNTEGRAProtocolOrNMGenieStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGEPETRawDataStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateGERTPlanStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePixelMedLegacyConvertedEnhancedCTImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePixelMedLegacyConvertedEnhancedMRImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePixelMedLegacyConvertedEnhancedPETImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePixelMedFloatingPointImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateSiemensCSANonImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateSiemensCTMRVolumeStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivateSiemensAXFrameSetsStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsSpecialisedXAStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsCXImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilips3DPresentationStateStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsVRMLStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsVolumeSetStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsVolumeStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsVolumeStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilips3DObjectStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilips3DObjectStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsSurfaceStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsSurfaceStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsCompositeObjectStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRCardioProfileStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRCardioStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRCardioStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsCTSyntheticImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRSyntheticImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRCardioAnalysisStorageRetired: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRCardioAnalysisStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsCXSyntheticImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsPerfusionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsPerfusionImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsXRayMFStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsLiveRunStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsRunStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsReconstructionStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRSpectrumStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRSeriesDataStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRColorImageStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePhilipsMRExamcardStorage: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly PrivatePMODMultiFrameImageStorage: string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static forName(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static forNameSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static nameOf(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static nameOfSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'org.dcm4che3.data.UID'
     */
    static newInstanceAsync(): Promise<UID>;
    constructor();
}
declare const UID_base: typeof UIDClass;
/**
 * Class org.dcm4che3.data.UID.
 *
 * This actually imports the java class for further use.
 * The class {@link UIDClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class UID extends UID_base {
}
export default UID;
//# sourceMappingURL=UID.d.ts.map