"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BiConsumer = exports.createBiConsumerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link BiConsumer} interface.
 * All required methods in {@link BiConsumerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createBiConsumerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.BiConsumer', methods, opts);
}
exports.createBiConsumerProxy = createBiConsumerProxy;
/**
 * Class java.util.function.BiConsumer.
 *
 * This actually imports the java class for further use.
 * The class {@link BiConsumerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BiConsumer extends (0, java_bridge_1.importClass)('java.util.function.BiConsumer') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.BiConsumer = BiConsumer;
exports.default = BiConsumer;
//# sourceMappingURL=BiConsumer.js.map