"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DoubleToLongFunction = exports.createDoubleToLongFunctionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link DoubleToLongFunction} interface.
 * All required methods in {@link DoubleToLongFunctionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDoubleToLongFunctionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.DoubleToLongFunction', methods, opts);
}
exports.createDoubleToLongFunctionProxy = createDoubleToLongFunctionProxy;
/**
 * Class java.util.function.DoubleToLongFunction.
 *
 * This actually imports the java class for further use.
 * The class {@link DoubleToLongFunctionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DoubleToLongFunction extends (0, java_bridge_1.importClass)('java.util.function.DoubleToLongFunction') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.DoubleToLongFunction = DoubleToLongFunction;
exports.default = DoubleToLongFunction;
//# sourceMappingURL=DoubleToLongFunction.js.map