"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IntConsumer = exports.createIntConsumerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IntConsumer} interface.
 * All required methods in {@link IntConsumerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIntConsumerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.IntConsumer', methods, opts);
}
exports.createIntConsumerProxy = createIntConsumerProxy;
/**
 * Class java.util.function.IntConsumer.
 *
 * This actually imports the java class for further use.
 * The class {@link IntConsumerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IntConsumer extends (0, java_bridge_1.importClass)('java.util.function.IntConsumer') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IntConsumer = IntConsumer;
exports.default = IntConsumer;
//# sourceMappingURL=IntConsumer.js.map