"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IntToLongFunction = exports.createIntToLongFunctionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IntToLongFunction} interface.
 * All required methods in {@link IntToLongFunctionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIntToLongFunctionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.IntToLongFunction', methods, opts);
}
exports.createIntToLongFunctionProxy = createIntToLongFunctionProxy;
/**
 * Class java.util.function.IntToLongFunction.
 *
 * This actually imports the java class for further use.
 * The class {@link IntToLongFunctionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IntToLongFunction extends (0, java_bridge_1.importClass)('java.util.function.IntToLongFunction') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IntToLongFunction = IntToLongFunction;
exports.default = IntToLongFunction;
//# sourceMappingURL=IntToLongFunction.js.map