"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ObjDoubleConsumer = exports.createObjDoubleConsumerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ObjDoubleConsumer} interface.
 * All required methods in {@link ObjDoubleConsumerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createObjDoubleConsumerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.ObjDoubleConsumer', methods, opts);
}
exports.createObjDoubleConsumerProxy = createObjDoubleConsumerProxy;
/**
 * Class java.util.function.ObjDoubleConsumer.
 *
 * This actually imports the java class for further use.
 * The class {@link ObjDoubleConsumerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ObjDoubleConsumer extends (0, java_bridge_1.importClass)('java.util.function.ObjDoubleConsumer') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ObjDoubleConsumer = ObjDoubleConsumer;
exports.default = ObjDoubleConsumer;
//# sourceMappingURL=ObjDoubleConsumer.js.map