"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Predicate = exports.createPredicateProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Predicate} interface.
 * All required methods in {@link PredicateInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createPredicateProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.Predicate', methods, opts);
}
exports.createPredicateProxy = createPredicateProxy;
/**
 * Class java.util.function.Predicate.
 *
 * This actually imports the java class for further use.
 * The class {@link PredicateClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Predicate extends (0, java_bridge_1.importClass)('java.util.function.Predicate') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Predicate = Predicate;
exports.default = Predicate;
//# sourceMappingURL=Predicate.js.map