"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnaryOperator = exports.createUnaryOperatorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link UnaryOperator} interface.
 * All required methods in {@link UnaryOperatorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createUnaryOperatorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.UnaryOperator', methods, opts);
}
exports.createUnaryOperatorProxy = createUnaryOperatorProxy;
/**
 * Class java.util.function.UnaryOperator.
 *
 * This actually imports the java class for further use.
 * The class {@link UnaryOperatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class UnaryOperator extends (0, java_bridge_1.importClass)('java.util.function.UnaryOperator') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.UnaryOperator = UnaryOperator;
exports.default = UnaryOperator;
//# sourceMappingURL=UnaryOperator.js.map