"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CFindSCPInject = exports.createCFindSCPInjectProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link CFindSCPInject} interface.
 * All required methods in {@link CFindSCPInjectInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createCFindSCPInjectProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.github.chinlinlee.dcm777.net.CFindSCPInject', methods, opts);
}
exports.createCFindSCPInjectProxy = createCFindSCPInjectProxy;
/**
 * Class org.github.chinlinlee.dcm777.net.CFindSCPInject.
 *
 * This actually imports the java class for further use.
 * The class {@link CFindSCPInjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CFindSCPInject extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.CFindSCPInject') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.CFindSCPInject = CFindSCPInject;
exports.default = CFindSCPInject;
