"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InstanceQueryTaskInject = exports.createInstanceQueryTaskInjectProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link InstanceQueryTaskInject} interface.
 * All required methods in {@link InstanceQueryTaskInjectInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createInstanceQueryTaskInjectProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.github.chinlinlee.dcm777.net.InstanceQueryTaskInject', methods, opts);
}
exports.createInstanceQueryTaskInjectProxy = createInstanceQueryTaskInjectProxy;
/**
 * Class org.github.chinlinlee.dcm777.net.InstanceQueryTaskInject.
 *
 * This actually imports the java class for further use.
 * The class {@link InstanceQueryTaskInjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class InstanceQueryTaskInject extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.InstanceQueryTaskInject') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.InstanceQueryTaskInject = InstanceQueryTaskInject;
exports.default = InstanceQueryTaskInject;
