"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InstanceQueryTask = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.github.chinlinlee.dcm777.net.InstanceQueryTask.
 *
 * This actually imports the java class for further use.
 * The class {@link InstanceQueryTaskClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class InstanceQueryTask extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.InstanceQueryTask') {
}
exports.InstanceQueryTask = InstanceQueryTask;
exports.default = InstanceQueryTask;
