"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SeriesQueryTaskInject = exports.createSeriesQueryTaskInjectProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link SeriesQueryTaskInject} interface.
 * All required methods in {@link SeriesQueryTaskInjectInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSeriesQueryTaskInjectProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.github.chinlinlee.dcm777.net.SeriesQueryTaskInject', methods, opts);
}
exports.createSeriesQueryTaskInjectProxy = createSeriesQueryTaskInjectProxy;
/**
 * Class org.github.chinlinlee.dcm777.net.SeriesQueryTaskInject.
 *
 * This actually imports the java class for further use.
 * The class {@link SeriesQueryTaskInjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SeriesQueryTaskInject extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.SeriesQueryTaskInject') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.SeriesQueryTaskInject = SeriesQueryTaskInject;
exports.default = SeriesQueryTaskInject;
