"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleCStoreSCP = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.github.chinlinlee.dcm777.net.SimpleCStoreSCP.
 *
 * This actually imports the java class for further use.
 * The class {@link SimpleCStoreSCPClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SimpleCStoreSCP extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.SimpleCStoreSCP') {
}
exports.SimpleCStoreSCP = SimpleCStoreSCP;
exports.default = SimpleCStoreSCP;
