"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventListener = exports.createEventListenerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link EventListener} interface.
 * All required methods in {@link EventListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createEventListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.EventListener', methods, opts);
}
exports.createEventListenerProxy = createEventListenerProxy;
/**
 * Class java.util.EventListener.
 *
 * This actually imports the java class for further use.
 * The class {@link EventListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class EventListener extends (0, java_bridge_1.importClass)('java.util.EventListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.EventListener = EventListener;
exports.default = EventListener;
//# sourceMappingURL=EventListener.js.map