"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.List = exports.createListProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link List} interface.
 * All required methods in {@link ListInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createListProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.List', methods, opts);
}
exports.createListProxy = createListProxy;
/**
 * Class java.util.List.
 *
 * This actually imports the java class for further use.
 * The class {@link ListClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class List extends (0, java_bridge_1.importClass)('java.util.List') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.List = List;
exports.default = List;
//# sourceMappingURL=List.js.map