import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";
import { LongConsumer as java_util_function_LongConsumer, LongConsumerInterface as java_util_function_LongConsumerInterface } from "./function/LongConsumer";
import { IntConsumer as java_util_function_IntConsumer, IntConsumerInterface as java_util_function_IntConsumerInterface } from "./function/IntConsumer";
/**
 * This class just defines types, you should import {@link LongSummaryStatistics} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LongSummaryStatisticsClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    accept(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    acceptSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    accept(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    acceptSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.util.LongSummaryStatistics'
     * @return original return type: 'void'
     */
    combine(var0: LongSummaryStatisticsClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.LongSummaryStatistics'
     * @return original return type: 'void'
     */
    combineSync(var0: LongSummaryStatisticsClass | null): void;
    /**
     * @return original return type: 'long'
     */
    getCount(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    getCountSync(): number;
    /**
     * @return original return type: 'long'
     */
    getSum(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    getSumSync(): number;
    /**
     * @return original return type: 'long'
     */
    getMin(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    getMinSync(): number;
    /**
     * @return original return type: 'double'
     */
    getAverage(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getAverageSync(): number;
    /**
     * @return original return type: 'long'
     */
    getMax(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    getMaxSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.function.LongConsumer'
     */
    andThen(var0: java_util_function_LongConsumer | JavaInterfaceProxy<java_util_function_LongConsumerInterface> | null): Promise<java_util_function_LongConsumer | null>;
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.function.LongConsumer'
     */
    andThenSync(var0: java_util_function_LongConsumer | JavaInterfaceProxy<java_util_function_LongConsumerInterface> | null): java_util_function_LongConsumer | null;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    andThen(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null): Promise<java_util_function_IntConsumer | null>;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    andThenSync(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null): java_util_function_IntConsumer | null;
    /**
     * @return original return type: 'java.util.LongSummaryStatistics'
     */
    static newInstanceAsync(): Promise<LongSummaryStatistics>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @param var3 original type: 'long'
     * @return original return type: 'java.util.LongSummaryStatistics'
     */
    static newInstanceAsync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number, var3: java_lang_Long | bigint | number): Promise<LongSummaryStatistics>;
    constructor();
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @param var3 original type: 'long'
     */
    constructor(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number, var3: java_lang_Long | bigint | number);
}
declare const LongSummaryStatistics_base: typeof LongSummaryStatisticsClass;
/**
 * Class java.util.LongSummaryStatistics.
 *
 * This actually imports the java class for further use.
 * The class {@link LongSummaryStatisticsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LongSummaryStatistics extends LongSummaryStatistics_base {
}
export default LongSummaryStatistics;
//# sourceMappingURL=LongSummaryStatistics.d.ts.map