import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IntStream as java_util_stream_IntStream } from "./stream/IntStream";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Supplier as java_util_function_Supplier, SupplierInterface as java_util_function_SupplierInterface } from "./function/Supplier";
import { IntConsumer as java_util_function_IntConsumer, IntConsumerInterface as java_util_function_IntConsumerInterface } from "./function/IntConsumer";
import { Runnable as java_lang_Runnable, RunnableInterface as java_lang_RunnableInterface } from "./../lang/Runnable";
import { IntSupplier as java_util_function_IntSupplier, IntSupplierInterface as java_util_function_IntSupplierInterface } from "./function/IntSupplier";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";
/**
 * This class just defines types, you should import {@link OptionalInt} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class OptionalIntClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    isEmpty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEmptySync(): boolean;
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    stream(): Promise<java_util_stream_IntStream | null>;
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    streamSync(): java_util_stream_IntStream | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.util.OptionalInt'
     */
    static of(var0: java_lang_Integer | number): Promise<OptionalInt | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.util.OptionalInt'
     */
    static ofSync(var0: java_lang_Integer | number): OptionalInt | null;
    /**
     * @return original return type: 'java.util.OptionalInt'
     */
    static empty(): Promise<OptionalInt | null>;
    /**
     * @return original return type: 'java.util.OptionalInt'
     */
    static emptySync(): OptionalInt | null;
    /**
     * @return original return type: 'boolean'
     */
    isPresent(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isPresentSync(): boolean;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'int'
     */
    orElse(var0: java_lang_Integer | number): Promise<number>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'int'
     */
    orElseSync(var0: java_lang_Integer | number): number;
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'int'
     */
    orElseThrow(var0: java_util_function_Supplier | JavaInterfaceProxy<java_util_function_SupplierInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'int'
     */
    orElseThrowSync(var0: java_util_function_Supplier | JavaInterfaceProxy<java_util_function_SupplierInterface> | null): number;
    /**
     * @return original return type: 'int'
     */
    orElseThrow(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    orElseThrowSync(): number;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'void'
     */
    ifPresent(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'void'
     */
    ifPresentSync(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null): void;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @param var1 original type: 'java.lang.Runnable'
     * @return original return type: 'void'
     */
    ifPresentOrElse(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null, var1: java_lang_Runnable | JavaInterfaceProxy<java_lang_RunnableInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @param var1 original type: 'java.lang.Runnable'
     * @return original return type: 'void'
     */
    ifPresentOrElseSync(var0: java_util_function_IntConsumer | JavaInterfaceProxy<java_util_function_IntConsumerInterface> | null, var1: java_lang_Runnable | JavaInterfaceProxy<java_lang_RunnableInterface> | null): void;
    /**
     * @param var0 original type: 'java.util.function.IntSupplier'
     * @return original return type: 'int'
     */
    orElseGet(var0: java_util_function_IntSupplier | JavaInterfaceProxy<java_util_function_IntSupplierInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'java.util.function.IntSupplier'
     * @return original return type: 'int'
     */
    orElseGetSync(var0: java_util_function_IntSupplier | JavaInterfaceProxy<java_util_function_IntSupplierInterface> | null): number;
    /**
     * @return original return type: 'int'
     */
    getAsInt(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getAsIntSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const OptionalInt_base: typeof OptionalIntClass;
/**
 * Class java.util.OptionalInt.
 *
 * This actually imports the java class for further use.
 * The class {@link OptionalIntClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class OptionalInt extends OptionalInt_base {
}
export default OptionalInt;
//# sourceMappingURL=OptionalInt.d.ts.map