"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Spliterator$OfInt = exports.createSpliterator$OfIntProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Spliterator$OfInt} interface.
 * All required methods in {@link Spliterator$OfIntInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSpliterator$OfIntProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.Spliterator$OfInt', methods, opts);
}
exports.createSpliterator$OfIntProxy = createSpliterator$OfIntProxy;
/**
 * Class java.util.Spliterator$OfInt.
 *
 * This actually imports the java class for further use.
 * The class {@link Spliterator$OfIntClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Spliterator$OfInt extends (0, java_bridge_1.importClass)('java.util.Spliterator$OfInt') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Spliterator$OfInt = Spliterator$OfInt;
exports.default = Spliterator$OfInt;
//# sourceMappingURL=Spliterator$OfInt.js.map