"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DicomInputStream = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.dcm4che3.io.DicomInputStream.
 *
 * This actually imports the java class for further use.
 * The class {@link DicomInputStreamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DicomInputStream extends (0, java_bridge_1.importClass)('org.dcm4che3.io.DicomInputStream') {
}
exports.DicomInputStream = DicomInputStream;
exports.default = DicomInputStream;
//# sourceMappingURL=DicomInputStream.js.map