import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { FlavorEvent as java_awt_datatransfer_FlavorEvent } from "./FlavorEvent";
/**
 * This class just defines types, you should import {@link FlavorListener} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FlavorListenerClass extends JavaClass {
    /**
     * @param var0 original type: 'java.awt.datatransfer.FlavorEvent'
     * @return original return type: 'void'
     */
    flavorsChanged(var0: java_awt_datatransfer_FlavorEvent | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.datatransfer.FlavorEvent'
     * @return original return type: 'void'
     */
    flavorsChangedSync(var0: java_awt_datatransfer_FlavorEvent | null): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createFlavorListenerProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface FlavorListenerInterface {
    /**
     * @param var0 original type: 'java.awt.datatransfer.FlavorEvent'
     * @return original return type: 'void'
     */
    flavorsChanged(var0: java_awt_datatransfer_FlavorEvent | null): void;
}
/**
 * Create a proxy for the {@link FlavorListener} interface.
 * All required methods in {@link FlavorListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createFlavorListenerProxy(methods: FlavorListenerInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<FlavorListenerInterface>;
declare const FlavorListener_base: typeof FlavorListenerClass;
/**
 * Class java.awt.datatransfer.FlavorListener.
 *
 * This actually imports the java class for further use.
 * The class {@link FlavorListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FlavorListener extends FlavorListener_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default FlavorListener;
//# sourceMappingURL=FlavorListener.d.ts.map