"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlgorithmParameterSpec = exports.createAlgorithmParameterSpecProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AlgorithmParameterSpec} interface.
 * All required methods in {@link AlgorithmParameterSpecInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAlgorithmParameterSpecProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.security.spec.AlgorithmParameterSpec', methods, opts);
}
exports.createAlgorithmParameterSpecProxy = createAlgorithmParameterSpecProxy;
/**
 * Class java.security.spec.AlgorithmParameterSpec.
 *
 * This actually imports the java class for further use.
 * The class {@link AlgorithmParameterSpecClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AlgorithmParameterSpec extends (0, java_bridge_1.importClass)('java.security.spec.AlgorithmParameterSpec') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AlgorithmParameterSpec = AlgorithmParameterSpec;
exports.default = AlgorithmParameterSpec;
