"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditMessages$EventActionCode = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.dcm4che3.audit.AuditMessages$EventActionCode.
 *
 * This actually imports the java class for further use.
 * The class {@link AuditMessages$EventActionCodeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AuditMessages$EventActionCode extends (0, java_bridge_1.importClass)('org.dcm4che3.audit.AuditMessages$EventActionCode') {
}
exports.AuditMessages$EventActionCode = AuditMessages$EventActionCode;
exports.default = AuditMessages$EventActionCode;
