/// <reference types="node" />
import { JavaClass, BasicOrJavaType } from "java-bridge";
import { ParticipantObjectIDTypeCode as org_dcm4che3_audit_ParticipantObjectIDTypeCode } from "./ParticipantObjectIDTypeCode";
import { ParticipantObjectDescription as org_dcm4che3_audit_ParticipantObjectDescription } from "./ParticipantObjectDescription";
import { List as java_util_List } from "./../../../java/util/List";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link ParticipantObjectIdentification} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ParticipantObjectIdentificationClass extends JavaClass {
    /**
     * @return original return type: 'org.dcm4che3.audit.ParticipantObjectIDTypeCode'
     */
    getParticipantObjectIDTypeCode(): Promise<org_dcm4che3_audit_ParticipantObjectIDTypeCode | null>;
    /**
     * @return original return type: 'org.dcm4che3.audit.ParticipantObjectIDTypeCode'
     */
    getParticipantObjectIDTypeCodeSync(): org_dcm4che3_audit_ParticipantObjectIDTypeCode | null;
    /**
     * @return original return type: 'org.dcm4che3.audit.ParticipantObjectDescription'
     */
    getParticipantObjectDescription(): Promise<org_dcm4che3_audit_ParticipantObjectDescription | null>;
    /**
     * @return original return type: 'org.dcm4che3.audit.ParticipantObjectDescription'
     */
    getParticipantObjectDescriptionSync(): org_dcm4che3_audit_ParticipantObjectDescription | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectID(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectIDSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectTypeCodeRole(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectTypeCodeRoleSync(var0: string | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectName(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectNameSync(var0: string | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectDataLifeCycle(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectDataLifeCycleSync(var0: string | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectNameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectID(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectIDSync(var0: string | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectTypeCode(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectTypeCodeSync(var0: string | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectTypeCodeRole(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectTypeCodeRoleSync(): string | null;
    /**
     * @return original return type: 'byte[]'
     */
    getParticipantObjectQuery(): Promise<Buffer | null>;
    /**
     * @return original return type: 'byte[]'
     */
    getParticipantObjectQuerySync(): Buffer | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getParticipantObjectDetail(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getParticipantObjectDetailSync(): java_util_List | null;
    /**
     * @param var0 original type: 'org.dcm4che3.audit.ParticipantObjectIDTypeCode'
     * @return original return type: 'void'
     */
    setParticipantObjectIDTypeCode(var0: org_dcm4che3_audit_ParticipantObjectIDTypeCode | null): Promise<void>;
    /**
     * @param var0 original type: 'org.dcm4che3.audit.ParticipantObjectIDTypeCode'
     * @return original return type: 'void'
     */
    setParticipantObjectIDTypeCodeSync(var0: org_dcm4che3_audit_ParticipantObjectIDTypeCode | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectSensitivity(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectSensitivitySync(): string | null;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    setParticipantObjectQuery(var0: Buffer | null): Promise<void>;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    setParticipantObjectQuerySync(var0: Buffer | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectTypeCode(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectTypeCodeSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectSensitivity(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setParticipantObjectSensitivitySync(var0: string | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectDataLifeCycle(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParticipantObjectDataLifeCycleSync(): string | null;
    /**
     * @param var0 original type: 'org.dcm4che3.audit.ParticipantObjectDescription'
     * @return original return type: 'void'
     */
    setParticipantObjectDescription(var0: org_dcm4che3_audit_ParticipantObjectDescription | null): Promise<void>;
    /**
     * @param var0 original type: 'org.dcm4che3.audit.ParticipantObjectDescription'
     * @return original return type: 'void'
     */
    setParticipantObjectDescriptionSync(var0: org_dcm4che3_audit_ParticipantObjectDescription | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'org.dcm4che3.audit.ParticipantObjectIdentification'
     */
    static newInstanceAsync(): Promise<ParticipantObjectIdentification>;
    constructor();
}
declare const ParticipantObjectIdentification_base: typeof ParticipantObjectIdentificationClass;
/**
 * Class org.dcm4che3.audit.ParticipantObjectIdentification.
 *
 * This actually imports the java class for further use.
 * The class {@link ParticipantObjectIdentificationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ParticipantObjectIdentification extends ParticipantObjectIdentification_base {
}
export default ParticipantObjectIdentification;
//# sourceMappingURL=ParticipantObjectIdentification.d.ts.map