"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InputMethodHighlight = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.im.InputMethodHighlight.
 *
 * This actually imports the java class for further use.
 * The class {@link InputMethodHighlightClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class InputMethodHighlight extends (0, java_bridge_1.importClass)('java.awt.im.InputMethodHighlight') {
}
exports.InputMethodHighlight = InputMethodHighlight;
exports.default = InputMethodHighlight;
//# sourceMappingURL=InputMethodHighlight.js.map