"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Subject = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class javax.security.auth.Subject.
 *
 * This actually imports the java class for further use.
 * The class {@link SubjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Subject extends (0, java_bridge_1.importClass)('javax.security.auth.Subject') {
}
exports.Subject = Subject;
exports.default = Subject;
//# sourceMappingURL=Subject.js.map