import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
/**
 * This class just defines types, you should import {@link WatchEvent$Modifier} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class WatchEvent$ModifierClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createWatchEvent$ModifierProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface WatchEvent$ModifierInterface {
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): string | null;
}
/**
 * Create a proxy for the {@link WatchEvent$Modifier} interface.
 * All required methods in {@link WatchEvent$ModifierInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createWatchEvent$ModifierProxy(methods: WatchEvent$ModifierInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<WatchEvent$ModifierInterface>;
declare const WatchEvent$Modifier_base: typeof WatchEvent$ModifierClass;
/**
 * Class java.nio.file.WatchEvent$Modifier.
 *
 * This actually imports the java class for further use.
 * The class {@link WatchEvent$ModifierClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class WatchEvent$Modifier extends WatchEvent$Modifier_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default WatchEvent$Modifier;
//# sourceMappingURL=WatchEvent$Modifier.d.ts.map