"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WatchEvent$Modifier = exports.createWatchEvent$ModifierProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link WatchEvent$Modifier} interface.
 * All required methods in {@link WatchEvent$ModifierInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createWatchEvent$ModifierProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.nio.file.WatchEvent$Modifier', methods, opts);
}
exports.createWatchEvent$ModifierProxy = createWatchEvent$ModifierProxy;
/**
 * Class java.nio.file.WatchEvent$Modifier.
 *
 * This actually imports the java class for further use.
 * The class {@link WatchEvent$ModifierClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class WatchEvent$Modifier extends (0, java_bridge_1.importClass)('java.nio.file.WatchEvent$Modifier') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.WatchEvent$Modifier = WatchEvent$Modifier;
exports.default = WatchEvent$Modifier;
//# sourceMappingURL=WatchEvent$Modifier.js.map