"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OffsetTime = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.time.OffsetTime.
 *
 * This actually imports the java class for further use.
 * The class {@link OffsetTimeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class OffsetTime extends (0, java_bridge_1.importClass)('java.time.OffsetTime') {
}
exports.OffsetTime = OffsetTime;
exports.default = OffsetTime;
//# sourceMappingURL=OffsetTime.js.map