import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Boolean as java_lang_Boolean } from "./../../../../java/lang/Boolean";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link Dcm2JpgExecutor$ConvertStatus} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Dcm2JpgExecutor$ConvertStatusClass extends JavaClass {
    /**
     * Original type: 'java.lang.Boolean'
     */
    status: java_lang_Boolean | boolean | null;
    /**
     * Original type: 'java.lang.String'
     */
    message: string | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'org.github.chinlinlee.dcm2jpg.Dcm2JpgExecutor$ConvertStatus'
     */
    static newInstance(): Promise<Dcm2JpgExecutor$ConvertStatus>;
    constructor();
}
declare const Dcm2JpgExecutor$ConvertStatus_base: typeof Dcm2JpgExecutor$ConvertStatusClass;
/**
 * Class org.github.chinlinlee.dcm2jpg.Dcm2JpgExecutor$ConvertStatus.
 *
 * This actually imports the java class for further use.
 * The class {@link Dcm2JpgExecutor$ConvertStatusClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Dcm2JpgExecutor$ConvertStatus extends Dcm2JpgExecutor$ConvertStatus_base {
}
export default Dcm2JpgExecutor$ConvertStatus;
//# sourceMappingURL=Dcm2JpgExecutor$ConvertStatus.d.ts.map