"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dcm2JpgExecutor = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.github.chinlinlee.dcm2jpg.Dcm2JpgExecutor.
 *
 * This actually imports the java class for further use.
 * The class {@link Dcm2JpgExecutorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Dcm2JpgExecutor extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm2jpg.Dcm2JpgExecutor') {
}
exports.Dcm2JpgExecutor = Dcm2JpgExecutor;
exports.default = Dcm2JpgExecutor;
//# sourceMappingURL=Dcm2JpgExecutor.js.map