"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffineTransform = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.geom.AffineTransform.
 *
 * This actually imports the java class for further use.
 * The class {@link AffineTransformClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AffineTransform extends (0, java_bridge_1.importClass)('java.awt.geom.AffineTransform') {
}
exports.AffineTransform = AffineTransform;
exports.default = AffineTransform;
//# sourceMappingURL=AffineTransform.js.map