"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonGenerator = exports.createJsonGeneratorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link JsonGenerator} interface.
 * All required methods in {@link JsonGeneratorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createJsonGeneratorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.json.stream.JsonGenerator', methods, opts);
}
exports.createJsonGeneratorProxy = createJsonGeneratorProxy;
/**
 * Class javax.json.stream.JsonGenerator.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonGeneratorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonGenerator extends (0, java_bridge_1.importClass)('javax.json.stream.JsonGenerator') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.JsonGenerator = JsonGenerator;
exports.default = JsonGenerator;
//# sourceMappingURL=JsonGenerator.js.map