"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonParser$Event = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class javax.json.stream.JsonParser$Event.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonParser$EventClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonParser$Event extends (0, java_bridge_1.importClass)('javax.json.stream.JsonParser$Event') {
}
exports.JsonParser$Event = JsonParser$Event;
exports.default = JsonParser$Event;
//# sourceMappingURL=JsonParser$Event.js.map