"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccessibleAction = exports.createAccessibleActionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AccessibleAction} interface.
 * All required methods in {@link AccessibleActionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAccessibleActionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.accessibility.AccessibleAction', methods, opts);
}
exports.createAccessibleActionProxy = createAccessibleActionProxy;
/**
 * Class javax.accessibility.AccessibleAction.
 *
 * This actually imports the java class for further use.
 * The class {@link AccessibleActionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AccessibleAction extends (0, java_bridge_1.importClass)('javax.accessibility.AccessibleAction') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AccessibleAction = AccessibleAction;
exports.default = AccessibleAction;
//# sourceMappingURL=AccessibleAction.js.map