"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccessibleText = exports.createAccessibleTextProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AccessibleText} interface.
 * All required methods in {@link AccessibleTextInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAccessibleTextProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.accessibility.AccessibleText', methods, opts);
}
exports.createAccessibleTextProxy = createAccessibleTextProxy;
/**
 * Class javax.accessibility.AccessibleText.
 *
 * This actually imports the java class for further use.
 * The class {@link AccessibleTextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AccessibleText extends (0, java_bridge_1.importClass)('javax.accessibility.AccessibleText') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AccessibleText = AccessibleText;
exports.default = AccessibleText;
//# sourceMappingURL=AccessibleText.js.map