"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DragSourceDragEvent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.dnd.DragSourceDragEvent.
 *
 * This actually imports the java class for further use.
 * The class {@link DragSourceDragEventClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DragSourceDragEvent extends (0, java_bridge_1.importClass)('java.awt.dnd.DragSourceDragEvent') {
}
exports.DragSourceDragEvent = DragSourceDragEvent;
exports.default = DragSourceDragEvent;
//# sourceMappingURL=DragSourceDragEvent.js.map