"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DragSourceMotionListener = exports.createDragSourceMotionListenerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link DragSourceMotionListener} interface.
 * All required methods in {@link DragSourceMotionListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDragSourceMotionListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.dnd.DragSourceMotionListener', methods, opts);
}
exports.createDragSourceMotionListenerProxy = createDragSourceMotionListenerProxy;
/**
 * Class java.awt.dnd.DragSourceMotionListener.
 *
 * This actually imports the java class for further use.
 * The class {@link DragSourceMotionListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DragSourceMotionListener extends (0, java_bridge_1.importClass)('java.awt.dnd.DragSourceMotionListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.DragSourceMotionListener = DragSourceMotionListener;
exports.default = DragSourceMotionListener;
//# sourceMappingURL=DragSourceMotionListener.js.map