"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DropTargetContext = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.dnd.DropTargetContext.
 *
 * This actually imports the java class for further use.
 * The class {@link DropTargetContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DropTargetContext extends (0, java_bridge_1.importClass)('java.awt.dnd.DropTargetContext') {
}
exports.DropTargetContext = DropTargetContext;
exports.default = DropTargetContext;
//# sourceMappingURL=DropTargetContext.js.map