"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseStream = exports.createBaseStreamProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link BaseStream} interface.
 * All required methods in {@link BaseStreamInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createBaseStreamProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.stream.BaseStream', methods, opts);
}
exports.createBaseStreamProxy = createBaseStreamProxy;
/**
 * Class java.util.stream.BaseStream.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseStreamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BaseStream extends (0, java_bridge_1.importClass)('java.util.stream.BaseStream') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.BaseStream = BaseStream;
exports.default = BaseStream;
//# sourceMappingURL=BaseStream.js.map