"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Collector$Characteristics = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.util.stream.Collector$Characteristics.
 *
 * This actually imports the java class for further use.
 * The class {@link Collector$CharacteristicsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Collector$Characteristics extends (0, java_bridge_1.importClass)('java.util.stream.Collector$Characteristics') {
}
exports.Collector$Characteristics = Collector$Characteristics;
exports.default = Collector$Characteristics;
//# sourceMappingURL=Collector$Characteristics.js.map