"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HierarchyListener = exports.createHierarchyListenerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link HierarchyListener} interface.
 * All required methods in {@link HierarchyListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createHierarchyListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.event.HierarchyListener', methods, opts);
}
exports.createHierarchyListenerProxy = createHierarchyListenerProxy;
/**
 * Class java.awt.event.HierarchyListener.
 *
 * This actually imports the java class for further use.
 * The class {@link HierarchyListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class HierarchyListener extends (0, java_bridge_1.importClass)('java.awt.event.HierarchyListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.HierarchyListener = HierarchyListener;
exports.default = HierarchyListener;
//# sourceMappingURL=HierarchyListener.js.map