import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { MouseEvent as java_awt_event_MouseEvent } from "./MouseEvent";
/**
 * This class just defines types, you should import {@link MouseMotionListener} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MouseMotionListenerClass extends JavaClass {
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseMoved(var0: java_awt_event_MouseEvent | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseMovedSync(var0: java_awt_event_MouseEvent | null): void;
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseDragged(var0: java_awt_event_MouseEvent | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseDraggedSync(var0: java_awt_event_MouseEvent | null): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createMouseMotionListenerProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface MouseMotionListenerInterface {
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseMoved(var0: java_awt_event_MouseEvent | null): void;
    /**
     * @param var0 original type: 'java.awt.event.MouseEvent'
     * @return original return type: 'void'
     */
    mouseDragged(var0: java_awt_event_MouseEvent | null): void;
}
/**
 * Create a proxy for the {@link MouseMotionListener} interface.
 * All required methods in {@link MouseMotionListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createMouseMotionListenerProxy(methods: MouseMotionListenerInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<MouseMotionListenerInterface>;
declare const MouseMotionListener_base: typeof MouseMotionListenerClass;
/**
 * Class java.awt.event.MouseMotionListener.
 *
 * This actually imports the java class for further use.
 * The class {@link MouseMotionListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MouseMotionListener extends MouseMotionListener_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default MouseMotionListener;
//# sourceMappingURL=MouseMotionListener.d.ts.map