"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MouseListener = exports.createMouseListenerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link MouseListener} interface.
 * All required methods in {@link MouseListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMouseListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.event.MouseListener', methods, opts);
}
exports.createMouseListenerProxy = createMouseListenerProxy;
/**
 * Class java.awt.event.MouseListener.
 *
 * This actually imports the java class for further use.
 * The class {@link MouseListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class MouseListener extends (0, java_bridge_1.importClass)('java.awt.event.MouseListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.MouseListener = MouseListener;
exports.default = MouseListener;
//# sourceMappingURL=MouseListener.js.map