"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowListener = exports.createWindowListenerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link WindowListener} interface.
 * All required methods in {@link WindowListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createWindowListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.event.WindowListener', methods, opts);
}
exports.createWindowListenerProxy = createWindowListenerProxy;
/**
 * Class java.awt.event.WindowListener.
 *
 * This actually imports the java class for further use.
 * The class {@link WindowListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class WindowListener extends (0, java_bridge_1.importClass)('java.awt.event.WindowListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.WindowListener = WindowListener;
exports.default = WindowListener;
//# sourceMappingURL=WindowListener.js.map