"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryRetrieveLevel2 = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.dcm4che3.net.service.QueryRetrieveLevel2.
 *
 * This actually imports the java class for further use.
 * The class {@link QueryRetrieveLevel2Class} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class QueryRetrieveLevel2 extends (0, java_bridge_1.importClass)('org.dcm4che3.net.service.QueryRetrieveLevel2') {
}
exports.QueryRetrieveLevel2 = QueryRetrieveLevel2;
exports.default = QueryRetrieveLevel2;
