import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../java/util/List";
import { Boolean as java_lang_Boolean } from "./../../../../java/lang/Boolean";
import { Association as org_dcm4che3_net_Association } from "./../../net/Association";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { Dimse as org_dcm4che3_net_Dimse } from "./../../net/Dimse";
import { PresentationContext as org_dcm4che3_net_pdu_PresentationContext } from "./../../net/pdu/PresentationContext";
import { Attributes as org_dcm4che3_data_Attributes } from "./../../data/Attributes";
/**
 * This class just defines types, you should import {@link RetrieveTaskImpl} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RetrieveTaskImplClass extends JavaClass {
    /**
     * @return original return type: 'void'
     */
    run(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    runSync(): void;
    /**
     * @return original return type: 'int'
     */
    getStatus(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getStatusSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    isCMove(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isCMoveSync(): boolean;
    /**
     * @return original return type: 'void'
     */
    writePendingRSP(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    writePendingRSPSync(): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getCompleted(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getCompletedSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isCanceled(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isCanceledSync(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    getWarning(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getWarningSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getFailed(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getFailedSync(): java_util_List | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setSendPendingRSP(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setSendPendingRSPSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'org.dcm4che3.net.Association'
     */
    getStoreAssociation(): Promise<org_dcm4che3_net_Association | null>;
    /**
     * @return original return type: 'org.dcm4che3.net.Association'
     */
    getStoreAssociationSync(): org_dcm4che3_net_Association | null;
    /**
     * @return original return type: 'org.dcm4che3.net.Association'
     */
    getRequestAssociation(): Promise<org_dcm4che3_net_Association | null>;
    /**
     * @return original return type: 'org.dcm4che3.net.Association'
     */
    getRequestAssociationSync(): org_dcm4che3_net_Association | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setSendPendingRSPInterval(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setSendPendingRSPIntervalSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'org.dcm4che3.net.Association'
     * @return original return type: 'void'
     */
    onCancelRQ(var0: org_dcm4che3_net_Association | null): Promise<void>;
    /**
     * @param var0 original type: 'org.dcm4che3.net.Association'
     * @return original return type: 'void'
     */
    onCancelRQSync(var0: org_dcm4che3_net_Association | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.dcm4che3.net.Dimse'
     * @param var1 original type: 'org.dcm4che3.net.Association'
     * @param var2 original type: 'org.dcm4che3.net.pdu.PresentationContext'
     * @param var3 original type: 'org.dcm4che3.data.Attributes'
     * @param var4 original type: 'java.util.List'
     * @param var5 original type: 'org.dcm4che3.net.Association'
     * @param var6 original type: 'boolean'
     * @param var7 original type: 'int'
     * @return original return type: 'org.dcm4che3.tool.dcmqrscp.RetrieveTaskImpl'
     */
    static newInstanceAsync(var0: org_dcm4che3_net_Dimse | null, var1: org_dcm4che3_net_Association | null, var2: org_dcm4che3_net_pdu_PresentationContext | null, var3: org_dcm4che3_data_Attributes | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var5: org_dcm4che3_net_Association | null, var6: java_lang_Boolean | boolean, var7: java_lang_Integer | number): Promise<RetrieveTaskImpl>;
    /**
     * @param var0 original type: 'org.dcm4che3.net.Dimse'
     * @param var1 original type: 'org.dcm4che3.net.Association'
     * @param var2 original type: 'org.dcm4che3.net.pdu.PresentationContext'
     * @param var3 original type: 'org.dcm4che3.data.Attributes'
     * @param var4 original type: 'java.util.List'
     * @param var5 original type: 'org.dcm4che3.net.Association'
     * @param var6 original type: 'boolean'
     * @param var7 original type: 'int'
     */
    constructor(var0: org_dcm4che3_net_Dimse | null, var1: org_dcm4che3_net_Association | null, var2: org_dcm4che3_net_pdu_PresentationContext | null, var3: org_dcm4che3_data_Attributes | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var5: org_dcm4che3_net_Association | null, var6: java_lang_Boolean | boolean, var7: java_lang_Integer | number);
}
declare const RetrieveTaskImpl_base: typeof RetrieveTaskImplClass;
/**
 * Class org.dcm4che3.tool.dcmqrscp.RetrieveTaskImpl.
 *
 * This actually imports the java class for further use.
 * The class {@link RetrieveTaskImplClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RetrieveTaskImpl extends RetrieveTaskImpl_base {
}
export default RetrieveTaskImpl;
//# sourceMappingURL=RetrieveTaskImpl.d.ts.map