"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Option$Builder = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.apache.commons.cli.Option$Builder.
 *
 * This actually imports the java class for further use.
 * The class {@link Option$BuilderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Option$Builder extends (0, java_bridge_1.importClass)('org.apache.commons.cli.Option$Builder') {
}
exports.Option$Builder = Option$Builder;
exports.default = Option$Builder;
