"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AttributedCharacterIterator$Attribute = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.text.AttributedCharacterIterator$Attribute.
 *
 * This actually imports the java class for further use.
 * The class {@link AttributedCharacterIterator$AttributeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AttributedCharacterIterator$Attribute extends (0, java_bridge_1.importClass)('java.text.AttributedCharacterIterator$Attribute') {
}
exports.AttributedCharacterIterator$Attribute = AttributedCharacterIterator$Attribute;
exports.default = AttributedCharacterIterator$Attribute;
//# sourceMappingURL=AttributedCharacterIterator$Attribute.js.map