"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContentHandlerFactory = exports.createContentHandlerFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ContentHandlerFactory} interface.
 * All required methods in {@link ContentHandlerFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createContentHandlerFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.net.ContentHandlerFactory', methods, opts);
}
exports.createContentHandlerFactoryProxy = createContentHandlerFactoryProxy;
/**
 * Class java.net.ContentHandlerFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link ContentHandlerFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ContentHandlerFactory extends (0, java_bridge_1.importClass)('java.net.ContentHandlerFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ContentHandlerFactory = ContentHandlerFactory;
exports.default = ContentHandlerFactory;
//# sourceMappingURL=ContentHandlerFactory.js.map