"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SocketOption = exports.createSocketOptionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link SocketOption} interface.
 * All required methods in {@link SocketOptionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSocketOptionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.net.SocketOption', methods, opts);
}
exports.createSocketOptionProxy = createSocketOptionProxy;
/**
 * Class java.net.SocketOption.
 *
 * This actually imports the java class for further use.
 * The class {@link SocketOptionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SocketOption extends (0, java_bridge_1.importClass)('java.net.SocketOption') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.SocketOption = SocketOption;
exports.default = SocketOption;
//# sourceMappingURL=SocketOption.js.map