"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SocketImplFactory = exports.createSocketImplFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link SocketImplFactory} interface.
 * All required methods in {@link SocketImplFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSocketImplFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.net.SocketImplFactory', methods, opts);
}
exports.createSocketImplFactoryProxy = createSocketImplFactoryProxy;
/**
 * Class java.net.SocketImplFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link SocketImplFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SocketImplFactory extends (0, java_bridge_1.importClass)('java.net.SocketImplFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.SocketImplFactory = SocketImplFactory;
exports.default = SocketImplFactory;
//# sourceMappingURL=SocketImplFactory.js.map