"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MatchResult = exports.createMatchResultProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link MatchResult} interface.
 * All required methods in {@link MatchResultInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMatchResultProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.regex.MatchResult', methods, opts);
}
exports.createMatchResultProxy = createMatchResultProxy;
/**
 * Class java.util.regex.MatchResult.
 *
 * This actually imports the java class for further use.
 * The class {@link MatchResultClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class MatchResult extends (0, java_bridge_1.importClass)('java.util.regex.MatchResult') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.MatchResult = MatchResult;
exports.default = MatchResult;
