"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Long = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.Long.
 *
 * This actually imports the java class for further use.
 * The class {@link LongClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Long extends (0, java_bridge_1.importClass)('java.lang.Long') {
}
exports.Long = Long;
exports.default = Long;
//# sourceMappingURL=Long.js.map