"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModuleLayer = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.ModuleLayer.
 *
 * This actually imports the java class for further use.
 * The class {@link ModuleLayerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ModuleLayer extends (0, java_bridge_1.importClass)('java.lang.ModuleLayer') {
}
exports.ModuleLayer = ModuleLayer;
exports.default = ModuleLayer;
//# sourceMappingURL=ModuleLayer.js.map