"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StackTraceElement = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.StackTraceElement.
 *
 * This actually imports the java class for further use.
 * The class {@link StackTraceElementClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StackTraceElement extends (0, java_bridge_1.importClass)('java.lang.StackTraceElement') {
}
exports.StackTraceElement = StackTraceElement;
exports.default = StackTraceElement;
//# sourceMappingURL=StackTraceElement.js.map