"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StringBuffer = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.StringBuffer.
 *
 * This actually imports the java class for further use.
 * The class {@link StringBufferClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StringBuffer extends (0, java_bridge_1.importClass)('java.lang.StringBuffer') {
}
exports.StringBuffer = StringBuffer;
exports.default = StringBuffer;
//# sourceMappingURL=StringBuffer.js.map