"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Thread$State = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.Thread$State.
 *
 * This actually imports the java class for further use.
 * The class {@link Thread$StateClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Thread$State extends (0, java_bridge_1.importClass)('java.lang.Thread$State') {
}
exports.Thread$State = Thread$State;
exports.default = Thread$State;
//# sourceMappingURL=Thread$State.js.map