"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CancelRQHandler = exports.createCancelRQHandlerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link CancelRQHandler} interface.
 * All required methods in {@link CancelRQHandlerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createCancelRQHandlerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.dcm4che3.net.CancelRQHandler', methods, opts);
}
exports.createCancelRQHandlerProxy = createCancelRQHandlerProxy;
/**
 * Class org.dcm4che3.net.CancelRQHandler.
 *
 * This actually imports the java class for further use.
 * The class {@link CancelRQHandlerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CancelRQHandler extends (0, java_bridge_1.importClass)('org.dcm4che3.net.CancelRQHandler') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.CancelRQHandler = CancelRQHandler;
exports.default = CancelRQHandler;
