"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DimseRSP = exports.createDimseRSPProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link DimseRSP} interface.
 * All required methods in {@link DimseRSPInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDimseRSPProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.dcm4che3.net.DimseRSP', methods, opts);
}
exports.createDimseRSPProxy = createDimseRSPProxy;
/**
 * Class org.dcm4che3.net.DimseRSP.
 *
 * This actually imports the java class for further use.
 * The class {@link DimseRSPClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DimseRSP extends (0, java_bridge_1.importClass)('org.dcm4che3.net.DimseRSP') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.DimseRSP = DimseRSP;
exports.default = DimseRSP;
