"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MethodHandles$Lookup = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.invoke.MethodHandles$Lookup.
 *
 * This actually imports the java class for further use.
 * The class {@link MethodHandles$LookupClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class MethodHandles$Lookup extends (0, java_bridge_1.importClass)('java.lang.invoke.MethodHandles$Lookup') {
}
exports.MethodHandles$Lookup = MethodHandles$Lookup;
exports.default = MethodHandles$Lookup;
//# sourceMappingURL=MethodHandles$Lookup.js.map