"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VarHandle$AccessMode = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.invoke.VarHandle$AccessMode.
 *
 * This actually imports the java class for further use.
 * The class {@link VarHandle$AccessModeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class VarHandle$AccessMode extends (0, java_bridge_1.importClass)('java.lang.invoke.VarHandle$AccessMode') {
}
exports.VarHandle$AccessMode = VarHandle$AccessMode;
exports.default = VarHandle$AccessMode;
//# sourceMappingURL=VarHandle$AccessMode.js.map