import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonValue as javax_json_JsonValue, JsonValueInterface as javax_json_JsonValueInterface } from "./JsonValue";
/**
 * This class just defines types, you should import {@link JsonMergePatch} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonMergePatchClass extends JavaClass {
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'javax.json.JsonValue'
     */
    apply(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): Promise<javax_json_JsonValue | null>;
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'javax.json.JsonValue'
     */
    applySync(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): javax_json_JsonValue | null;
    /**
     * @return original return type: 'javax.json.JsonValue'
     */
    toJsonValue(): Promise<javax_json_JsonValue | null>;
    /**
     * @return original return type: 'javax.json.JsonValue'
     */
    toJsonValueSync(): javax_json_JsonValue | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonMergePatchProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonMergePatchInterface {
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'javax.json.JsonValue'
     */
    apply(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): javax_json_JsonValue | null;
    /**
     * @return original return type: 'javax.json.JsonValue'
     */
    toJsonValue(): javax_json_JsonValue | null;
}
/**
 * Create a proxy for the {@link JsonMergePatch} interface.
 * All required methods in {@link JsonMergePatchInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonMergePatchProxy(methods: JsonMergePatchInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonMergePatchInterface>;
declare const JsonMergePatch_base: typeof JsonMergePatchClass;
/**
 * Class javax.json.JsonMergePatch.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonMergePatchClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonMergePatch extends JsonMergePatch_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonMergePatch;
//# sourceMappingURL=JsonMergePatch.d.ts.map