import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonStructure as javax_json_JsonStructure, JsonStructureInterface as javax_json_JsonStructureInterface } from "./JsonStructure";
import { JsonValue as javax_json_JsonValue, JsonValueInterface as javax_json_JsonValueInterface } from "./JsonValue";
import { JsonObject as javax_json_JsonObject, JsonObjectInterface as javax_json_JsonObjectInterface } from "./JsonObject";
import { JsonArray as javax_json_JsonArray, JsonArrayInterface as javax_json_JsonArrayInterface } from "./JsonArray";
/**
 * This class just defines types, you should import {@link JsonWriter} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonWriterClass extends JavaClass {
    /**
     * @param var0 original type: 'javax.json.JsonStructure'
     * @return original return type: 'void'
     */
    write(var0: javax_json_JsonStructure | JavaInterfaceProxy<javax_json_JsonStructureInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.json.JsonStructure'
     * @return original return type: 'void'
     */
    writeSync(var0: javax_json_JsonStructure | JavaInterfaceProxy<javax_json_JsonStructureInterface> | null): void;
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'void'
     */
    write(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'void'
     */
    writeSync(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): void;
    /**
     * @param var0 original type: 'javax.json.JsonObject'
     * @return original return type: 'void'
     */
    writeObject(var0: javax_json_JsonObject | JavaInterfaceProxy<javax_json_JsonObjectInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.json.JsonObject'
     * @return original return type: 'void'
     */
    writeObjectSync(var0: javax_json_JsonObject | JavaInterfaceProxy<javax_json_JsonObjectInterface> | null): void;
    /**
     * @return original return type: 'void'
     */
    close(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    closeSync(): void;
    /**
     * @param var0 original type: 'javax.json.JsonArray'
     * @return original return type: 'void'
     */
    writeArray(var0: javax_json_JsonArray | JavaInterfaceProxy<javax_json_JsonArrayInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.json.JsonArray'
     * @return original return type: 'void'
     */
    writeArraySync(var0: javax_json_JsonArray | JavaInterfaceProxy<javax_json_JsonArrayInterface> | null): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonWriterProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonWriterInterface {
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'javax.json.JsonStructure'
     * @return original return type: 'void'
     */
    write?(var0: javax_json_JsonStructure | JavaInterfaceProxy<javax_json_JsonStructureInterface> | null): void;
    /**
     * @param var0 original type: 'javax.json.JsonValue'
     * @return original return type: 'void'
     */
    write?(var0: javax_json_JsonValue | JavaInterfaceProxy<javax_json_JsonValueInterface> | null): void;
    /**
     * @param var0 original type: 'javax.json.JsonObject'
     * @return original return type: 'void'
     */
    writeObject(var0: javax_json_JsonObject | JavaInterfaceProxy<javax_json_JsonObjectInterface> | null): void;
    /**
     * @return original return type: 'void'
     */
    close(): void;
    /**
     * @param var0 original type: 'javax.json.JsonArray'
     * @return original return type: 'void'
     */
    writeArray(var0: javax_json_JsonArray | JavaInterfaceProxy<javax_json_JsonArrayInterface> | null): void;
}
/**
 * Create a proxy for the {@link JsonWriter} interface.
 * All required methods in {@link JsonWriterInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonWriterProxy(methods: JsonWriterInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonWriterInterface>;
declare const JsonWriter_base: typeof JsonWriterClass;
/**
 * Class javax.json.JsonWriter.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonWriterClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonWriter extends JsonWriter_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonWriter;
//# sourceMappingURL=JsonWriter.d.ts.map