"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccessControlContext = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.security.AccessControlContext.
 *
 * This actually imports the java class for further use.
 * The class {@link AccessControlContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AccessControlContext extends (0, java_bridge_1.importClass)('java.security.AccessControlContext') {
}
exports.AccessControlContext = AccessControlContext;
exports.default = AccessControlContext;
//# sourceMappingURL=AccessControlContext.js.map