"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlgorithmParameters = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.security.AlgorithmParameters.
 *
 * This actually imports the java class for further use.
 * The class {@link AlgorithmParametersClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AlgorithmParameters extends (0, java_bridge_1.importClass)('java.security.AlgorithmParameters') {
}
exports.AlgorithmParameters = AlgorithmParameters;
exports.default = AlgorithmParameters;
