"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyStore$ProtectionParameter = exports.createKeyStore$ProtectionParameterProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link KeyStore$ProtectionParameter} interface.
 * All required methods in {@link KeyStore$ProtectionParameterInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createKeyStore$ProtectionParameterProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.security.KeyStore$ProtectionParameter', methods, opts);
}
exports.createKeyStore$ProtectionParameterProxy = createKeyStore$ProtectionParameterProxy;
/**
 * Class java.security.KeyStore$ProtectionParameter.
 *
 * This actually imports the java class for further use.
 * The class {@link KeyStore$ProtectionParameterClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class KeyStore$ProtectionParameter extends (0, java_bridge_1.importClass)('java.security.KeyStore$ProtectionParameter') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.KeyStore$ProtectionParameter = KeyStore$ProtectionParameter;
exports.default = KeyStore$ProtectionParameter;
