"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyStore$Entry = exports.createKeyStore$EntryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link KeyStore$Entry} interface.
 * All required methods in {@link KeyStore$EntryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createKeyStore$EntryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.security.KeyStore$Entry', methods, opts);
}
exports.createKeyStore$EntryProxy = createKeyStore$EntryProxy;
/**
 * Class java.security.KeyStore$Entry.
 *
 * This actually imports the java class for further use.
 * The class {@link KeyStore$EntryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class KeyStore$Entry extends (0, java_bridge_1.importClass)('java.security.KeyStore$Entry') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.KeyStore$Entry = KeyStore$Entry;
exports.default = KeyStore$Entry;
