import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Permission as java_security_Permission } from "./Permission";
import { Enumeration as java_util_Enumeration } from "./../util/Enumeration";
import { Stream as java_util_stream_Stream } from "./../util/stream/Stream";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";
/**
 * This class just defines types, you should import {@link PermissionCollection} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PermissionCollectionClass extends JavaClass {
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    add(var0: java_security_Permission | null): Promise<void>;
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    addSync(var0: java_security_Permission | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    elements(): Promise<java_util_Enumeration | null>;
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    elementsSync(): java_util_Enumeration | null;
    /**
     * @return original return type: 'void'
     */
    setReadOnly(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    setReadOnlySync(): void;
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    implies(var0: java_security_Permission | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    impliesSync(var0: java_security_Permission | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnly(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnlySync(): boolean;
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    elementsAsStream(): Promise<java_util_stream_Stream | null>;
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    elementsAsStreamSync(): java_util_stream_Stream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const PermissionCollection_base: typeof PermissionCollectionClass;
/**
 * Class java.security.PermissionCollection.
 *
 * This actually imports the java class for further use.
 * The class {@link PermissionCollectionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PermissionCollection extends PermissionCollection_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default PermissionCollection;
//# sourceMappingURL=PermissionCollection.d.ts.map