"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timestamp = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.security.Timestamp.
 *
 * This actually imports the java class for further use.
 * The class {@link TimestampClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Timestamp extends (0, java_bridge_1.importClass)('java.security.Timestamp') {
}
exports.Timestamp = Timestamp;
exports.default = Timestamp;
//# sourceMappingURL=Timestamp.js.map