"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoundingMode = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.math.RoundingMode.
 *
 * This actually imports the java class for further use.
 * The class {@link RoundingModeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class RoundingMode extends (0, java_bridge_1.importClass)('java.math.RoundingMode') {
}
exports.RoundingMode = RoundingMode;
exports.default = RoundingMode;
//# sourceMappingURL=RoundingMode.js.map