"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompositeContext = exports.createCompositeContextProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link CompositeContext} interface.
 * All required methods in {@link CompositeContextInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createCompositeContextProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.CompositeContext', methods, opts);
}
exports.createCompositeContextProxy = createCompositeContextProxy;
/**
 * Class java.awt.CompositeContext.
 *
 * This actually imports the java class for further use.
 * The class {@link CompositeContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CompositeContext extends (0, java_bridge_1.importClass)('java.awt.CompositeContext') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.CompositeContext = CompositeContext;
exports.default = CompositeContext;
//# sourceMappingURL=CompositeContext.js.map