import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Double as java_lang_Double } from "./../lang/Double";
import { Dimension2D as java_awt_geom_Dimension2D } from "./geom/Dimension2D";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";
/**
 * This class just defines types, you should import {@link Dimension} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DimensionClass extends JavaClass {
    /**
     * Original type: 'int'
     */
    width: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    height: java_lang_Integer | number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.awt.Dimension'
     */
    getSize(): Promise<Dimension | null>;
    /**
     * @return original return type: 'java.awt.Dimension'
     */
    getSizeSync(): Dimension | null;
    /**
     * @param var0 original type: 'java.awt.Dimension'
     * @return original return type: 'void'
     */
    setSize(var0: DimensionClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.Dimension'
     * @return original return type: 'void'
     */
    setSizeSync(var0: DimensionClass | null): void;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'void'
     */
    setSize(var0: java_lang_Double | number, var1: java_lang_Double | number): Promise<void>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'void'
     */
    setSizeSync(var0: java_lang_Double | number, var1: java_lang_Double | number): void;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    setSize(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    setSizeSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.awt.geom.Dimension2D'
     * @return original return type: 'void'
     */
    setSize(var0: java_awt_geom_Dimension2D | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.Dimension2D'
     * @return original return type: 'void'
     */
    setSizeSync(var0: java_awt_geom_Dimension2D | null): void;
    /**
     * @return original return type: 'double'
     */
    getHeight(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getHeightSync(): number;
    /**
     * @return original return type: 'double'
     */
    getWidth(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getWidthSync(): number;
    /**
     * @return original return type: 'java.lang.Object'
     */
    clone(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    cloneSync(): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.awt.Dimension'
     * @return original return type: 'java.awt.Dimension'
     */
    static newInstanceAsync(var0: DimensionClass | null): Promise<Dimension>;
    /**
     * @return original return type: 'java.awt.Dimension'
     */
    static newInstanceAsync(): Promise<Dimension>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.awt.Dimension'
     */
    static newInstanceAsync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<Dimension>;
    /**
     * @param var0 original type: 'java.awt.Dimension'
     */
    constructor(var0: DimensionClass | null);
    constructor();
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     */
    constructor(var0: java_lang_Integer | number, var1: java_lang_Integer | number);
}
declare const Dimension_base: typeof DimensionClass;
/**
 * Class java.awt.Dimension.
 *
 * This actually imports the java class for further use.
 * The class {@link DimensionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Dimension extends Dimension_base {
}
export default Dimension;
//# sourceMappingURL=Dimension.d.ts.map