"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Font = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.Font.
 *
 * This actually imports the java class for further use.
 * The class {@link FontClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Font extends (0, java_bridge_1.importClass)('java.awt.Font') {
}
exports.Font = Font;
exports.default = Font;
//# sourceMappingURL=Font.js.map