"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Insets = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.Insets.
 *
 * This actually imports the java class for further use.
 * The class {@link InsetsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Insets extends (0, java_bridge_1.importClass)('java.awt.Insets') {
}
exports.Insets = Insets;
exports.default = Insets;
//# sourceMappingURL=Insets.js.map