"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobAttributes$MultipleDocumentHandlingType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.JobAttributes$MultipleDocumentHandlingType.
 *
 * This actually imports the java class for further use.
 * The class {@link JobAttributes$MultipleDocumentHandlingTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JobAttributes$MultipleDocumentHandlingType extends (0, java_bridge_1.importClass)('java.awt.JobAttributes$MultipleDocumentHandlingType') {
}
exports.JobAttributes$MultipleDocumentHandlingType = JobAttributes$MultipleDocumentHandlingType;
exports.default = JobAttributes$MultipleDocumentHandlingType;
//# sourceMappingURL=JobAttributes$MultipleDocumentHandlingType.js.map