"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobAttributes = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.JobAttributes.
 *
 * This actually imports the java class for further use.
 * The class {@link JobAttributesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JobAttributes extends (0, java_bridge_1.importClass)('java.awt.JobAttributes') {
}
exports.JobAttributes = JobAttributes;
exports.default = JobAttributes;
//# sourceMappingURL=JobAttributes.js.map