"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobAttributes$DialogType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.JobAttributes$DialogType.
 *
 * This actually imports the java class for further use.
 * The class {@link JobAttributes$DialogTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JobAttributes$DialogType extends (0, java_bridge_1.importClass)('java.awt.JobAttributes$DialogType') {
}
exports.JobAttributes$DialogType = JobAttributes$DialogType;
exports.default = JobAttributes$DialogType;
//# sourceMappingURL=JobAttributes$DialogType.js.map