"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageAttributes$MediaType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.PageAttributes$MediaType.
 *
 * This actually imports the java class for further use.
 * The class {@link PageAttributes$MediaTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class PageAttributes$MediaType extends (0, java_bridge_1.importClass)('java.awt.PageAttributes$MediaType') {
}
exports.PageAttributes$MediaType = PageAttributes$MediaType;
exports.default = PageAttributes$MediaType;
//# sourceMappingURL=PageAttributes$MediaType.js.map