"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageAttributes$OriginType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.awt.PageAttributes$OriginType.
 *
 * This actually imports the java class for further use.
 * The class {@link PageAttributes$OriginTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class PageAttributes$OriginType extends (0, java_bridge_1.importClass)('java.awt.PageAttributes$OriginType') {
}
exports.PageAttributes$OriginType = PageAttributes$OriginType;
exports.default = PageAttributes$OriginType;
//# sourceMappingURL=PageAttributes$OriginType.js.map