import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Shape as java_awt_Shape, ShapeInterface as java_awt_ShapeInterface } from "./Shape";
/**
 * This class just defines types, you should import {@link Stroke} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class StrokeClass extends JavaClass {
    /**
     * @param var0 original type: 'java.awt.Shape'
     * @return original return type: 'java.awt.Shape'
     */
    createStrokedShape(var0: java_awt_Shape | JavaInterfaceProxy<java_awt_ShapeInterface> | null): Promise<java_awt_Shape | null>;
    /**
     * @param var0 original type: 'java.awt.Shape'
     * @return original return type: 'java.awt.Shape'
     */
    createStrokedShapeSync(var0: java_awt_Shape | JavaInterfaceProxy<java_awt_ShapeInterface> | null): java_awt_Shape | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createStrokeProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface StrokeInterface {
    /**
     * @param var0 original type: 'java.awt.Shape'
     * @return original return type: 'java.awt.Shape'
     */
    createStrokedShape(var0: java_awt_Shape | JavaInterfaceProxy<java_awt_ShapeInterface> | null): java_awt_Shape | null;
}
/**
 * Create a proxy for the {@link Stroke} interface.
 * All required methods in {@link StrokeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createStrokeProxy(methods: StrokeInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<StrokeInterface>;
declare const Stroke_base: typeof StrokeClass;
/**
 * Class java.awt.Stroke.
 *
 * This actually imports the java class for further use.
 * The class {@link StrokeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Stroke extends Stroke_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default Stroke;
//# sourceMappingURL=Stroke.d.ts.map