"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Chronology = exports.createChronologyProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Chronology} interface.
 * All required methods in {@link ChronologyInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createChronologyProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.time.chrono.Chronology', methods, opts);
}
exports.createChronologyProxy = createChronologyProxy;
/**
 * Class java.time.chrono.Chronology.
 *
 * This actually imports the java class for further use.
 * The class {@link ChronologyClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Chronology extends (0, java_bridge_1.importClass)('java.time.chrono.Chronology') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Chronology = Chronology;
exports.default = Chronology;
//# sourceMappingURL=Chronology.js.map