"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModuleDescriptor$Exports = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.lang.module.ModuleDescriptor$Exports.
 *
 * This actually imports the java class for further use.
 * The class {@link ModuleDescriptor$ExportsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ModuleDescriptor$Exports extends (0, java_bridge_1.importClass)('java.lang.module.ModuleDescriptor$Exports') {
}
exports.ModuleDescriptor$Exports = ModuleDescriptor$Exports;
exports.default = ModuleDescriptor$Exports;
//# sourceMappingURL=ModuleDescriptor$Exports.js.map